### ISSUE TITLE
can't build the project

### ISSUE THREAD

**Issue by ndar12** [Wikitude/wikitude-sdk-samples#6]
Hi,
I'm trying to buid the project "wikitude-sdk-samples" in my XamarinStudio verion 5.9.3(build 1). I have Xamarin Android Player - Nexus 5 (Lollipop) Android 5.1.0, API 21.

I have been following the steps under "Wikitude Sample App - Getting Started quickly" on:
http://www.wikitude.com/external/doc/documentation/latest/xamarin/setupguidexamarin.html

However, the errors after lunching the debugger are:
1) File not found: C:\prj_XAMARIN AR\wikitude-xamarin-master\wikitude-xamarin-master\source\binding\Android\JARTOXML

2)File not found: C:\prj_XAMARIN AR\wikitude-xamarin-master\wikitude-xamarin-master\source\binding\Android\BINDINGSGENERATOR

3)C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(5,5): Error MSB4018: The "LinkAssemblies" task failed unexpectedly.
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at MonoDroid.Tuner.PreserveApplications.PreserveTypeProperty(CustomAttribute attribute, String property)
   at MonoDroid.Tuner.PreserveApplications.ProcessAttributeProvider(ICustomAttributeProvider provider)
   at MonoDroid.Tuner.PreserveApplications.ProcessAssembly(AssemblyDefinition assembly)
   at Mono.Tuner.SubStepDispatcher.DispatchAssembly(AssemblyDefinition assembly)
   at Mono.Tuner.SubStepDispatcher.BrowseAssemblies(IEnumerable`1 assemblies)
   at Mono.Tuner.SubStepDispatcher.Process(LinkContext context)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at MonoDroid.Tuner.Linker.Process(LinkerOptions options, LinkContext& context)
   at Xamarin.Android.Tasks.LinkAssemblies.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__20.MoveNext() (MSB4018) (WikitudeSampleAndroid)

An idea on why 1) and 2) files are missing, and why the linker gives errors despite Targe Framework of both projects  is Android 5.0 (Lollipop) would be appreciated.

**Comment by AndreasSchacherbauerWikitude** [comment]
Hi @ndar12, this repository only contains Architect Worlds which is something you can't build. Architect Worlds are something that is loaded by our Wikitude JS API SDK.
